version: "3.7"

services:
  php:
    container_name: php
    build:
      context: ./
      target: php
    ports:
      - "8000:9000"
    depends_on:
      - postgres
    volumes:
      - ../associacao:/src
    networks:
      - rede-interna
  nginx:
    container_name: nginx
    build:
      context: ./
      target: nginx
    ports:
      - 80:80
    volumes:
      - ./services/nginx/site.conf:/etc/nginx/sites-enabled/default
      - ./:/src
    environment:
      - LANG=pt_BR.utf8
      - LANGUAGE=pt_BR.utf8
      - LC_ALL=pt_BR.utf8
      - LC_TIME=pt_BR.utf8
      - LC_COLLATE=pt_BR.utf8
      - LC_CTYPE=pt_BR.utf8
      - LC_MESSAGES=pt_BR.utf8
      - LC_MONETARY=pt_BR.utf8
      - TZ=America/Sao_Paulo
    links:
      - php
    networks:
      - rede-interna
  postgres:
    container_name: postgres
    build:
      context: ./
      target: postgres

    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
      - LANG=pt_BR.utf8
      - LANGUAGE=pt_BR.utf8
      - LC_ALL=pt_BR.utf8
      - LC_TIME=pt_BR.utf8
      - LC_COLLATE=pt_BR.utf8
      - LC_CTYPE=pt_BR.utf8
      - LC_MESSAGES=pt_BR.utf8
      - LC_MONETARY=pt_BR.utf8
      - TZ=America/Sao_Paulo
      - POSTGRES_INITDB_ARGS=-E UTF-8
    command:
      - "postgres"
      - "-c"
      - "log_timezone=America/Sao_Paulo"
      - "-c"
      - "timezone=America/Sao_Paulo"
      - "-c"
      - "full_page_writes=off"
      - "-c"
      - "fsync=off"
      - "-c"
      - "synchronous_commit=off"
    networks:
      - rede-interna
networks:
  rede-interna:
    driver: bridge
